### ISSUE TITLE
Crash on startup with Android Studio?

### ISSUE THREAD

**Issue by BobbyWibowo** [Almighty-Alpaca/Intellij-Discord-Integration#13]
```java
Plugin 'com.almightyalpaca.intellij.plugins.discord' failed to initialize and will be disabled.  Please restart Android Studio.

java.lang.ExceptionInInitializerError
    at org.jgroups.logging.LogFactory.getLog(LogFactory.java:101)
    at org.jgroups.conf.XmlConfigurator.<clinit>(XmlConfigurator.java:33)
    at org.jgroups.conf.ConfiguratorFactory.getXmlConfigurator(ConfiguratorFactory.java:210)
    at org.jgroups.conf.ConfiguratorFactory.getStackConfigurator(ConfiguratorFactory.java:91)
    at org.jgroups.JChannel.<init>(JChannel.java:130)
    at com.almightyalpaca.intellij.plugins.discord.services.DiscordIntegrationApplicationService.init(DiscordIntegrationApplicationService.java:57)
    at com.almightyalpaca.intellij.plugins.discord.services.DiscordIntegrationApplicationService.checkInitialized(DiscordIntegrationApplicationService.java:200)
    at com.almightyalpaca.intellij.plugins.discord.components.DiscordIntegrationApplicationComponent.initComponent(DiscordIntegrationApplicationComponent.java:29)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:491)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:120)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$8(ApplicationImpl.java:466)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:473)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:104)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:425)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:411)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:206)
    at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:49)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:343)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NullPointerException
    at java.util.Locale.<init>(Locale.java:648)
    at java.util.Locale.<init>(Locale.java:677)
    at org.jgroups.logging.Slf4jLogImpl.<clinit>(Slf4jLogImpl.java:20)
    ... 37 more

```
```
Android Studio 3.0.1  Build #AI-171.4443003 
JDK: 1.8.0_152-release 
VM: OpenJDK 64-Bit Server VM 
Vendor: JetBrains s.r.o 
OS: Linux 
```
OS is KDE neon 5.11.4 (Ubuntu 16.04 LTS), to be more specific.

**Comment by Almighty-Alpaca** [comment]
The error happens while JGroups is trying to get the local of your system. It uses the `user.language` and `user.country` system properties for that but for some reasons at least one of those isn't set in your environment. I've added a little workaround for the next version, until then you can try to [set those properties yourself](https://intellij-support.jetbrains.com/hc/en-us/articles/206544869) as a temporary fix.
