### ISSUE TITLE
Random ConcurrentModificationException

### ISSUE THREAD

**Issue by austinv11** [Almighty-Alpaca/Intellij-Discord-Integration#19]
I was using this plugin on PyCharm when it suddenly spit out this error:
```
ailed processing requests: java.util.ConcurrentModificationException
java.lang.RuntimeException: java.util.ConcurrentModificationException
	at org.jgroups.blocks.MessageDispatcher$ProtocolAdapter.up(MessageDispatcher.java:574)
	at org.jgroups.JChannel.up(JChannel.java:797)
	at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:891)
	at org.jgroups.protocols.pbcast.STATE_TRANSFER.up(STATE_TRANSFER.java:122)
	at org.jgroups.protocols.RSVP.up(RSVP.java:158)
	at org.jgroups.protocols.FRAG2.up(FRAG2.java:163)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:338)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:338)
	at org.jgroups.protocols.pbcast.GMS.installView(GMS.java:702)
	at org.jgroups.protocols.pbcast.CoordGmsImpl.handleViewChange(CoordGmsImpl.java:219)
	at org.jgroups.protocols.pbcast.GMS.castViewChangeAndSendJoinRsps(GMS.java:587)
	at org.jgroups.protocols.pbcast.CoordGmsImpl.handleMembershipChange(CoordGmsImpl.java:197)
	at org.jgroups.protocols.pbcast.GMS.process(GMS.java:1297)
	at org.jgroups.protocols.pbcast.ViewHandler.removeAndProcess(ViewHandler.java:239)
	at org.jgroups.protocols.pbcast.ViewHandler.process(ViewHandler.java:203)
	at org.jgroups.protocols.pbcast.ViewHandler.add(ViewHandler.java:62)
	at org.jgroups.protocols.pbcast.GMS.up(GMS.java:881)
	at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:240)
	at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1002)
	at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:728)
	at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:383)
	at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:600)
	at org.jgroups.protocols.BARRIER.up(BARRIER.java:170)
	at org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:119)
	at org.jgroups.protocols.FD_ALL.up(FD_ALL.java:199)
	at org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:252)
	at org.jgroups.protocols.MERGE3.up(MERGE3.java:276)
	at org.jgroups.protocols.Discovery.up(Discovery.java:267)
	at org.jgroups.protocols.TP.passMessageUp(TP.java:1229)
	at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:87)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.almightyalpaca.intellij.plugins.discord.data.ReplicatedData.viewAccepted(ReplicatedData.java:560)
	at org.jgroups.blocks.MessageDispatcher.handleUpEvent(MessageDispatcher.java:511)
	at org.jgroups.blocks.MessageDispatcher$ProtocolAdapter.up(MessageDispatcher.java:571)
	... 32 more
```
Unfortunately I have no further information on how to replicate this as it happened seemingly randomly. If you need more info, I am happy to provide it.

**Comment by Almighty-Alpaca** [comment]
This should already be fixed in 7a54d80. I've released version v0.6.0 with that fix two days ago but Jetbrains can be very slow approving new versions (took up to 5 days in the past). It will be visible in the IDEs' plugin browsers once it has been approved.

**Comment by Almighty-Alpaca** [comment]
Update: it has been approved exactly 1 hour ago and should now be shown in all IDEs.
