### ISSUE TITLE
IPC Error

### ISSUE THREAD

**Issue by joaovmundel** [Almighty-Alpaca/Intellij-Discord-Integration#396]
> `java.lang.Throwable: IPC failed
> 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
> 	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$connect$2.invokeSuspend(DiscordIpcConnection.kt:150)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
> `

**Comment by ByThePowerOfScience** [comment]
Same issue.
```
java.lang.Throwable: IPC failed
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.rpc.connection.DiscordIpcConnection$connect$2.invokeSuspend(DiscordIpcConnection.kt:150)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

IntelliJ IDEA 2023.2.5 (Ultimate Edition)
Build #IU-232.10227.8, built on November 9, 2023
Runtime version: 17.0.9+7-b1000.46 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.7.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
Metal Rendering is ON
Non-Bundled Plugins:
    com.jetbrains.plugins.ini4idea (232.10203.2)
    Key Promoter X (2023.2.0)
    com.intellij.nativeDebug (232.10203.2)
    org.jetbrains.jumpToLine (0.1.14)
    com.jetbrains.packagesearch.intellij-plugin (232.9921.28)
    org.jetbrains.kotlin (232-1.9.20-release-507-IJ10072.27)
    com.hotswap.agent.plugin (1.3.0)
    com.jetbrains.idea.safepush (232.8660.88)
    com.almightyalpaca.intellij.plugins.discord (1.12.0)
    com.demonwav.minecraft-dev (2023.2-1.6.10)
    Pythonid (232.10227.8)
    mobi.hsz.idea.gitignore (4.5.2)

Kotlin: 232-1.9.20-release-507-IJ10072.27

Error occurred while I was loading a Bukkit project from the start page.  The project visibility setting is set to "App only", and Discord was not running at the time.

**Comment by Uninstal** [comment]
Run IDEA as an administrator, it solved my problem

**Comment by ByThePowerOfScience** [comment]
> Run IDEA as an administrator, it solved my problem

I'm on Mac, so I guess I'll sudo it.  But actually, I just realized that it wouldn't be too hard to PR a catch statement myself somewhere in there, so I'm gonna go do that.

EDIT: Ok, so after looking through the code, it looks like the only culprit would be Discord still having an IPC file despite not running.  I'm not sure how you'd detect if it's running or not, since the hook this plugin uses to interface with Discord just throws a generic `ConnectionError.FAILED` exception, so the next best thing is to not make the end user have to deal with it at all by lowering it to a warning.
