### ISSUE TITLE
PHPStorm 2023.3.* can't load a project

### ISSUE THREAD

**Issue by aolko** [Almighty-Alpaca/Intellij-Discord-Integration#399]
```
com.intellij.diagnostic.PluginException: cannot execute preloading activity com.almightyalpaca.jetbrains.plugins.discord.plugin.time.TimePreloadingActivity [Plugin: com.almightyalpaca.intellij.plugins.discord]
	at com.intellij.platform.ide.bootstrap.AppServicePreloadingKt.executePreloadActivity(appServicePreloading.kt:208)
	at com.intellij.platform.ide.bootstrap.AppServicePreloadingKt.access$executePreloadActivity(appServicePreloading.kt:1)
	at com.intellij.platform.ide.bootstrap.AppServicePreloadingKt$postAppRegistered$4$1.invokeSuspend(appServicePreloading.kt:189)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.AssertionError: Thread[DefaultDispatcher-worker-9,5,main]
	at com.intellij.ide.IdeEventQueue.<init>(IdeEventQueue.kt:140)
	at com.intellij.ide.IdeEventQueue.<init>(IdeEventQueue.kt)
	at com.intellij.ide.IdeEventQueue$Companion$_instance$2.invoke(IdeEventQueue.kt:160)
	at com.intellij.ide.IdeEventQueue$Companion$_instance$2.invoke(IdeEventQueue.kt:160)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.intellij.ide.IdeEventQueue$Companion.get_instance(IdeEventQueue.kt:160)
	at com.intellij.ide.IdeEventQueue$Companion.getInstance(IdeEventQueue.kt:163)
	at com.intellij.ide.IdeEventQueue.getInstance(IdeEventQueue.kt)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.time.TimeService.<init>(TimeService.kt:194)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt$instantiate$2.invoke(instantiate.kt:41)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt$instantiate$2.invoke(instantiate.kt:39)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt.instantiate(instantiate.kt:278)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt.instantiate(instantiate.kt:39)
	at com.intellij.serviceContainer.LightServiceInstanceSupport$LightServiceInstanceInitializer.createInstance(LightServiceInstanceSupport.kt:47)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invokeSuspend(LazyInstanceHolder.kt:162)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invokeSuspend(LazyInstanceHolder.kt:160)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.initialize(LazyInstanceHolder.kt:145)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.access$initialize(LazyInstanceHolder.kt:13)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.tryInitialize(LazyInstanceHolder.kt:135)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance(LazyInstanceHolder.kt:95)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstanceInCallerContext$suspendImpl(LazyInstanceHolder.kt:87)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstanceInCallerContext(LazyInstanceHolder.kt)
	at com.intellij.serviceContainer.ComponentManagerImplKt$getOrCreateInstanceBlocking$3.invokeSuspend(ComponentManagerImpl.kt:2337)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at com.intellij.serviceContainer.ComponentManagerImplKt$runBlockingInitialization$1.invoke(ComponentManagerImpl.kt:2406)
	at com.intellij.serviceContainer.ComponentManagerImplKt$runBlockingInitialization$1.invoke(ComponentManagerImpl.kt:2397)
	at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:86)
	at com.intellij.serviceContainer.ComponentManagerImplKt.runBlockingInitialization(ComponentManagerImpl.kt:2397)
	at com.intellij.serviceContainer.ComponentManagerImplKt.getOrCreateInstanceBlocking(ComponentManagerImpl.kt:2336)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:1057)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:988)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.time.TimeServiceKt.getTimeService(TimeService.kt:248)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.time.TimePreloadingActivity.preload(TimePreloadingActivity.kt:25)
	at com.intellij.openapi.application.PreloadingActivity$execute$2.invoke(PreloadingActivity.kt:15)
	at com.intellij.openapi.application.PreloadingActivity$execute$2.invoke(PreloadingActivity.kt:14)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:321)
	at com.intellij.openapi.progress.CoroutinesKt.access$blockingContextInner(coroutines.kt:1)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invokeSuspend(coroutines.kt:198)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:197)
	at com.intellij.openapi.application.PreloadingActivity.execute$suspendImpl(PreloadingActivity.kt:14)
	at com.intellij.openapi.application.PreloadingActivity.execute(PreloadingActivity.kt)
	at com.intellij.platform.ide.bootstrap.AppServicePreloadingKt.executePreloadActivity(appServicePreloading.kt:201)
	... 8 more
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@3c22a201, Dispatchers.Default]
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@24e9c7b5, Dispatchers.Default]

```

```
java.lang.AssertionError: Thread[DefaultDispatcher-worker-9,5,main]
	at com.intellij.ide.IdeEventQueue.<init>(IdeEventQueue.kt:140)
	at com.intellij.ide.IdeEventQueue.<init>(IdeEventQueue.kt)
	at com.intellij.ide.IdeEventQueue$Companion$_instance$2.invoke(IdeEventQueue.kt:160)
	at com.intellij.ide.IdeEventQueue$Companion$_instance$2.invoke(IdeEventQueue.kt:160)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.intellij.ide.IdeEventQueue$Companion.get_instance(IdeEventQueue.kt:160)
	at com.intellij.ide.IdeEventQueue$Companion.getInstance(IdeEventQueue.kt:163)
	at com.intellij.ide.IdeEventQueue.getInstance(IdeEventQueue.kt)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.time.TimeService.<init>(TimeService.kt:194)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt$instantiate$2.invoke(instantiate.kt:41)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt$instantiate$2.invoke(instantiate.kt:39)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt.instantiate(instantiate.kt:278)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt.instantiate(instantiate.kt:39)
	at com.intellij.serviceContainer.LightServiceInstanceSupport$LightServiceInstanceInitializer.createInstance(LightServiceInstanceSupport.kt:47)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invokeSuspend(LazyInstanceHolder.kt:162)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invokeSuspend(LazyInstanceHolder.kt:160)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.initialize(LazyInstanceHolder.kt:145)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.access$initialize(LazyInstanceHolder.kt:13)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.tryInitialize(LazyInstanceHolder.kt:135)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance(LazyInstanceHolder.kt:95)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstanceInCallerContext$suspendImpl(LazyInstanceHolder.kt:87)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstanceInCallerContext(LazyInstanceHolder.kt)
	at com.intellij.serviceContainer.ComponentManagerImplKt$getOrCreateInstanceBlocking$3.invokeSuspend(ComponentManagerImpl.kt:2337)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at com.intellij.serviceContainer.ComponentManagerImplKt$runBlockingInitialization$1.invoke(ComponentManagerImpl.kt:2406)
	at com.intellij.serviceContainer.ComponentManagerImplKt$runBlockingInitialization$1.invoke(ComponentManagerImpl.kt:2397)
	at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:86)
	at com.intellij.serviceContainer.ComponentManagerImplKt.runBlockingInitialization(ComponentManagerImpl.kt:2397)
	at com.intellij.serviceContainer.ComponentManagerImplKt.getOrCreateInstanceBlocking(ComponentManagerImpl.kt:2336)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:1057)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:988)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.time.TimeServiceKt.getTimeService(TimeService.kt:248)
	at com.almightyalpaca.jetbrains.plugins.discord.plugin.time.TimePreloadingActivity.preload(TimePreloadingActivity.kt:25)
	at com.intellij.openapi.application.PreloadingActivity$execute$2.invoke(PreloadingActivity.kt:15)
	at com.intellij.openapi.application.PreloadingActivity$execute$2.invoke(PreloadingActivity.kt:14)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:321)
	at com.intellij.openapi.progress.CoroutinesKt.access$blockingContextInner(coroutines.kt:1)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invokeSuspend(coroutines.kt:198)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:197)
	at com.intellij.openapi.application.PreloadingActivity.execute$suspendImpl(PreloadingActivity.kt:14)
	at com.intellij.openapi.application.PreloadingActivity.execute(PreloadingActivity.kt)
	at com.intellij.platform.ide.bootstrap.AppServicePreloadingKt.executePreloadActivity(appServicePreloading.kt:201)
	at com.intellij.platform.ide.bootstrap.AppServicePreloadingKt.access$executePreloadActivity(appServicePreloading.kt:1)
	at com.intellij.platform.ide.bootstrap.AppServicePreloadingKt$postAppRegistered$4$1.invokeSuspend(appServicePreloading.kt:189)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@3c22a201, Dispatchers.Default]
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@24e9c7b5, Dispatchers.Default]
```

**Comment by mister-svinia** [comment]
Similar problem in RustRover, IDEA, PyCharm.

**Comment by vitorsantosb** [comment]
Similar problem with WebStorm 2023.3.2v

**Comment by Wolf2323** [comment]
Similar problem with IntelliJ

**Comment by fakeman2332** [comment]
Plugin version: 1.12.0. The problem still actual and happens in (Rider, WebStorm, PHPStorm). Maybe in all IntelliJ-based IDEs.

**Comment by mister-svinia** [comment]
> Maybe in all IntelliJ-based IDEs.

Yes, of course it is. They're all compatible. (As they say, compatibility is also about mistakes).
Да, конечно, это так. Они все совместимы. (Как говорится, совместимость - это еще и ошибки).

**Comment by minhhieuphamit** [comment]
How to fix this error, it appears on both inteliji and pycharm

**Comment by Azn9** [comment]
I don't like to advertise on other projects, especially on the original project. But as these issues starts to cause problems with loading projects or even starting the IDE, I cannot let all the users without any help. I made a fork of this plugin a few month ago, with many bug fixes and some improvements. It is fully compatible for all IDEs incling 2024 EAP ones.
https://github.com/Azn9/JetBrains-Discord-Integration

**Comment by aolko** [comment]
> I don't like to advertise on other projects, especially on the original project. But as these issues starts to cause problems with loading projects or even starting the IDE, I cannot let all the users without any help. I made a fork of this plugin a few month ago, with many bug fixes and some improvements. It is fully compatible for all IDEs incling 2024 EAP ones. https://github.com/Azn9/JetBrains-Discord-Integration

Currently resorted to using that one
