### ISSUE TITLE
IDE error occurred

### ISSUE THREAD

**Issue by Meywy** [Almighty-Alpaca/Intellij-Discord-Integration#416]
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.almightyalpaca.jetbrains.plugins.discord.plugin.actions.ApplicationShowAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.almightyalpaca.intellij.plugins.discord]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

I'm running Fedora Workstation 40 and Intellij Idea Ultimate 2024.2 and the extension is throwing this error and not working.

**Comment by JakobHeubl** [comment]
I have this Issue also in the Rider EAP 2024.2 RC 1.

**Comment by Meywy** [comment]
> I have this Issue also in the Rider EAP 2024.2 RC 1.

I found out that it doesn't work in other ides too, we probably need just to wait for update.

**Comment by pascalecu** [comment]
I can confirm this issue occurs on IntelliJ IDEA Community 2024.2.

```
IntelliJ IDEA 2024.2 (Community Edition)
Build #IC-242.20224.300, built on August 6, 2024
Runtime version: 21.0.3+13-b509.4 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 6.1.0-23-amd64
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Non-Bundled Plugins:
  com.intellij.classic.ui (242.20224.159)
  com.intellij.ideolog (242.20224.214)
  name.kropp.intellij.makefile (242.20224.155)
  Docker (242.20224.237)
  net.seesharpsoft.intellij.plugins.csv (2.21.0)
  com.almightyalpaca.intellij.plugins.discord (1.12.0)
  zielu.gittoolbox (500.2.14+242)
  MavenRunHelper (4.28.0-IJ2022.2)
  com.cursiveclojure.cursive (1.13.5-2024.2)
Kotlin: 242.20224.300-IJ
Current Desktop: GNOME
```

**Comment by Meywy** [comment]
> I can confirm this issue occurs on IntelliJ IDEA Community 2024.2.
> 
> ```
> IntelliJ IDEA 2024.2 (Community Edition)
> Build #IC-242.20224.300, built on August 6, 2024
> Runtime version: 21.0.3+13-b509.4 amd64 (JCEF 122.1.9)
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> Toolkit: sun.awt.X11.XToolkit
> Linux 6.1.0-23-amd64
> GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
> Memory: 2048M
> Cores: 8
> Non-Bundled Plugins:
>   com.intellij.classic.ui (242.20224.159)
>   com.intellij.ideolog (242.20224.214)
>   name.kropp.intellij.makefile (242.20224.155)
>   Docker (242.20224.237)
>   net.seesharpsoft.intellij.plugins.csv (2.21.0)
>   com.almightyalpaca.intellij.plugins.discord (1.12.0)
>   zielu.gittoolbox (500.2.14+242)
>   MavenRunHelper (4.28.0-IJ2022.2)
>   com.cursiveclojure.cursive (1.13.5-2024.2)
> Kotlin: 242.20224.300-IJ
> Current Desktop: GNOME
> ```

Hey, If you are looking for the fix you can use this plugin: https://plugins.jetbrains.com/plugin/23420-discord-integration-v2
It is basically the same plugin, but maintained by someone else, since the original dev stopped updating the plugin.
