### ISSUE TITLE
Internal Error always by interacting with Discord Integration

### ISSUE THREAD

**Issue by swnck** [Almighty-Alpaca/Intellij-Discord-Integration#420]
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.almightyalpaca.jetbrains.plugins.discord.plugin.actions.ApplicationShowAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.almightyalpaca.intellij.plugins.discord]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

```

Intellji Idea: 2024.2.3 
Plugin Version: 1.20.0

**Comment by swnck** [comment]
Its like an exception.
