### ISSUE TITLE
Issue on Latest Intellij IDEA

### ISSUE THREAD

**Issue by Kai-Denzel-Jane** [Almighty-Alpaca/Intellij-Discord-Integration#422]
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.almightyalpaca.jetbrains.plugins.discord.plugin.actions.ApplicationShowAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.almightyalpaca.intellij.plugins.discord]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

```

OS: WIndows 11
Intellij IDEA Version: Latest Release (Community)

**Comment by 301haru** [comment]
having same problem, need to force render update every time.

**Comment by 301haru** [comment]
#421 
there's PR already, actually.

**Comment by TheDaChicken** [comment]
There's a fork here for the time being https://github.com/Azn9/JetBrains-Discord-Integration
